export class UserModel {
    public Name:string = "";
    public SurName:string = "";
    public UserName:string = "";
    public Token:string = "";
    public EMail:string = "";
    public EMailVerifi:boolean = false;
    public PhoneNumber:string = "";
    public Address1:string = "";
    public Address2:string = "";
    public City:string = "";
    public State:string = "";
    public ZipCode:string = "";
    public Photo:string = "";
    public GooglePhoto:string = "";
    public TimeZone:string = "";
    public UserType:string = "User";
    public LicenseFeaturesId:number = 1;
    public Id:string = "";
    public AddedDate:string = "";
    public ModifiedDate:string = "";
}